version: '3.7'

services:

  blog:
    build:
      context: ./services/flask
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@blog-db:5432/blog_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@blog-db:5432/blog_test
    depends_on:
      - blog-db
  
  blog-db:
    build:
      context: ./services/flask/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres