version: '3.7'

services:

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=blog/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=blog.config.DevelopmentConfig