version: '3.7'

services:

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=blog/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=blog.config.DevelopmentConfig

  
  blog-db:  # new
    build:
      context: ./blog/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres